server:
  port: 8080

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop # ???? ??? ??? ??? ??
#    properties:
#      hibernate:
#        format_sql: true # SQL ? ?? ???? ???
#        show_sql: true # SQL ???
#  datasource:
#    password: ohgiraffers
#    username: ohgiraffers
#    url: jdbc:mysql://localhost:3306/ohgiraffers
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#jwt: # ??? ??? ??? ??
#  key: sdfadsfsdfadsfasdfasdfasdfsdfnw4tn23n4on1k5n1k2n14369hn
#  time: 86400000

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # ???? ??? ??? ??? ??
    properties:
      hibernate:
        format_sql: true # SQL ? ?? ???? ???
        show_sql: true # SQL ???
  datasource:
    password: finaldb
    username: finaldb
    url: jdbc:mysql://localhost:3306/finaldb
    driver-class-name: com.mysql.cj.jdbc.Driver